version: '3'
services:
  ngx-mat-color-picker:
    build: ./
    image: ngx-mat-color-picker 
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - 4201:4200
      - 9877:9876
    command: ng serve --host 0.0.0.0 --port 4200 --poll=1000 --disable-host-check
